### ISSUE TITLE
你写的文章真好！！！

### ISSUE THREAD

**Issue by laik** [reng99/blogs#109]
as title

**Comment by reng99** [comment]
> 

Thank you

**Comment by dengliming** [comment]
见到熟人了？

**Comment by laik** [comment]
> 见到熟人了？

are you ok?

**Comment by dengliming** [comment]
![006I1bcHgy1gs8u8zttl6j30sg0ug1ai](https://user-images.githubusercontent.com/7796156/151325593-7dbdb7c6-d8cb-4a74-97a2-cbd811b087d1.jpg)

**Comment by reng99** [comment]
> 见到熟人了？

How about you? Bro

**Comment by reng99** [comment]
Thanks for communicating. This Issues will be closed after one minutes later. Welcome for other message.
